### ISSUE TITLE
`Azure Dev Provision`  failed to run  in action logs

### ISSUE THREAD

**Issue by v-jiaodi** [Azure-Samples/apptemplate-wordpress-on-aca#11]
**Describe the issue:**
After providing  required value as repository secrets to be used by the GitHub Actions workflow, execute the `azure-dev.yml` action workflow.
The following error was encountered.

![image](https://user-images.githubusercontent.com/80496810/224275866-d6e257ca-7ba9-4c70-942f-cbb0038bea9a.png)

**Repro Steps:**
1. Fork the repository https://github.com/Azure-Samples/apptemplate-wordpress-on-aca.
2. Create an Azure Service Principal.
3. Store the required value as GitHub Actions secrets.
4. Execute the `azure-dev.yml` action workflow.

**Expected behavior:**
Workflow can deploy resources normally.

@kpantos for notification.

**Comment by michalorac** [comment]
looking forward to the update
