### ISSUE TITLE
Invalid request body for container app.

### ISSUE THREAD

**Issue by zedy-wj** [Azure-Samples/apptemplate-wordpress-on-aca#13]
**Describe the issue:**
When executing the `azd provision` command, provisioning resource failed.

**Repro Steps:**

1. azd init -t <template_name>
2. azd package
3. azd provision with deployWithRedis is off (Enter a random string when prompted)
![image](https://user-images.githubusercontent.com/81678720/230879495-f66e4b69-c9b7-473a-921e-6ef4f1d0d0d1.png)
4. azd provision with deployWithRedis is on (Enter a random string when prompted)
![image](https://user-images.githubusercontent.com/81678720/230879584-0d44097b-e500-4e6a-8f95-5d9b3cebfc60.png)

Notes: Are we randomly entering a string based on the prompt? Or where to get these special values?

**Environment:**
OS: Windows
Azd version: azd version 0.8.0-beta.1-daily.2689578 (commit 3b28fc8f84717d732f646a3e3b9521204f122112)

**Expected behavior:**
Executing `azd provision` can pass.

@rajeshkamal5050, @kpantos for notification.

**Comment by puicchan** [comment]
@kpantos, I just tried the app template with the latest azd build. I ran into the same issue:

Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'wordpressapp-deployment' is not valid according to the validation procedure. TContainerAppInvalidSchema: Invalid request body for container app. Path: $[6]. Does not conform to Container App schema, please visit for more information https://docs.microsoft.com/azure/container-apps/azure-resource-manager-api-spec?tabs=arm-template#container-app

Can you take a look? 

@aarthiem as FYI.
