### ISSUE TITLE
End of support Azure Database for MariaDB for creating over Azure Portal / CLI

### ISSUE THREAD

**Issue by ghost** [Azure-Samples/apptemplate-wordpress-on-aca#20]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> In alignment with the Azure Database for MariaDB retirement announcement, we stopped support for creating MariaDB instances via the Azure portal or CLI as of March 19, 2024.
https://learn.microsoft.com/en-us/azure/mariadb/whats-happening-to-mariadb

### Any log messages given by the failure
> Deployment Error Details: InvalidElasticServerType: The provided server type value 'Azure Database for MariaDB - Single Server' is invalid.

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by alexweininger** [comment]
Having the same issue

**Comment by reegan-anne** [comment]
Changing [this line](https://github.com/Azure-Samples/apptemplate-wordpress-on-aca/blob/4cc7624578dcedd38c2ba830b0a3727e42bc76b8/infra/resources.bicep#L117) to 'true' resolved it for me

**Comment by kpantos** [comment]
MariaDB service has been removed with Azure Database for MySQL flexible server.
