### ISSUE TITLE
Add -t to `azd up` to simplify deploy instruction for azd

### ISSUE THREAD

**Issue by puicchan** [Azure-Samples/apptemplate-wordpress-on-aca#3]
Once issue #2 is addressed, instead of git clone and then `azd init`. you can just do `azd up -t apptemplate-wordpress-aca`

**Comment by kpantos** [comment]
Implementation of issue #2 is complete.
Documentation has also been changed to leverage `azd up` instead of manually adding the azure environment variables

**Comment by puicchan** [comment]
You can simplify README by asking customer to run `azd up -t apptemplate-wordpress-on-aca` **in an empty folder** as a single step. `azd up` is `azd init` + `azd provision` + `azd deploy` so the 1st step in your readme is included.
